name: template-ts-dev-env
services:
  app:
    entrypoint:
    - sleep
    - infinity
    build:
      context: ./.devcontainer
      dockerfile: ./dev.Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    init: true