name: ci

on: [push]

jobs:
  gqlnode-node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/gqlnode/
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Instal Dependencies
        run: npm install

      - name: Instal Dependencies
        run: npm run lint

      - name: Test
        run: npm test
  reactnode-react:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/reactnode/react/
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Instal Dependencies
        run: npm install

      - name: Instal Dependencies
        run: npm run lint

      - name: Test
        run: npm test
  reactnode-node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/reactnode/node/
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Instal Dependencies
        run: npm install

      - name: Instal Dependencies
        run: npm run lint

      - name: Test
        run: npm test
